package egain.oassdk.testgenerators.support;

import egain.oassdk.config.TestConfig;
import egain.oassdk.core.exceptions.GenerationException;
import egain.oassdk.testgenerators.common.TestOutputLayout;
import egain.oassdk.testgenerators.common.TestSpecUtils;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

/**
 * Emits shared test-support Java classes and {@code test-env.properties} template
 * used by all generated Java test modules.
 */
public class TestSupportGenerator {

    public void generate(Map<String, Object> spec, String outputDir, TestConfig config) throws GenerationException {
        try {
            String basePackage = resolvePackage(config);
            String supportPackage = TestOutputLayout.supportPackage(basePackage);
            String defaultBaseUrl = TestSpecUtils.resolveBaseUrl(spec, config);
            boolean egainAuth = TestSpecUtils.useEgainAuth(config, spec);

            Path supportDir = Paths.get(TestOutputLayout.supportJavaDir(outputDir, basePackage));
            Files.createDirectories(supportDir);

            write(supportDir.resolve("TestEnv.java"), testEnvSource(supportPackage, defaultBaseUrl));
            write(supportDir.resolve("TestAuth.java"), testAuthSource(supportPackage, egainAuth));
            write(supportDir.resolve("TestHttp.java"), testHttpSource(supportPackage));
            write(supportDir.resolve("TestClient.java"), testClientSource(supportPackage));
            write(supportDir.resolve("TestContext.java"), testContextSource(supportPackage));
            if (egainAuth) {
                write(supportDir.resolve("EgainAuth.java"), egainAuthSource(supportPackage));
            }

            Path testsRoot = Paths.get(outputDir);
            Files.createDirectories(testsRoot);
            write(testsRoot.resolve("test-env.properties"), testEnvProperties(defaultBaseUrl, egainAuth));
            write(testsRoot.resolve("test-env.local.properties.example"), testEnvLocalExample(egainAuth));
            write(testsRoot.resolve("run-smoke.sh"), runSmokeScript());
            write(testsRoot.resolve("run-smoke.bat"), runSmokeBat());
            write(testsRoot.resolve("pom.xml"), aggregatorPom());
            write(testsRoot.resolve("README-TESTS.md"), readmeTests(egainAuth));

        } catch (IOException e) {
            throw new GenerationException("Failed to generate test support: " + e.getMessage(), e);
        }
    }

    private static String resolvePackage(TestConfig config) {
        if (config != null && config.getAdditionalProperties() != null) {
            Object pkg = config.getAdditionalProperties().get("packageName");
            if (pkg != null && !pkg.toString().isBlank()) {
                return pkg.toString().trim();
            }
        }
        return "com.example.api";
    }

    private static void write(Path path, String content) throws IOException {
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }

    private static String testEnvSource(String pkg, String defaultBaseUrl) {
        return """
                package %s;

                import java.io.InputStream;
                import java.nio.file.Files;
                import java.nio.file.Path;
                import java.util.Locale;
                import java.util.Properties;

                /**
                 * Loads test-env.properties (+ optional local override) and environment variables.
                 * Generated by OAS SDK TestSupportGenerator.
                 */
                public final class TestEnv {

                    private static final Properties PROPS = loadProperties();

                    private TestEnv() {
                    }

                    private static Properties loadProperties() {
                        Properties p = new Properties();
                        loadFile(p, resolveEnvFile());
                        loadFile(p, siblingFile("test-env.local.properties"));
                        return p;
                    }

                    private static String resolveEnvFile() {
                        String env = System.getenv("TEST_ENV_FILE");
                        if (env != null && !env.isBlank()) {
                            return env.trim();
                        }
                        return siblingPath("test-env.properties");
                    }

                    private static String siblingPath(String name) {
                        Path cwd = Path.of(System.getProperty("user.dir", ".")).toAbsolutePath().normalize();
                        Path parent = cwd.getParent();
                        if (parent != null && Files.isRegularFile(parent.resolve(name))) {
                            return parent.resolve(name).toString();
                        }
                        if (Files.isRegularFile(cwd.resolve(name))) {
                            return cwd.resolve(name).toString();
                        }
                        return name;
                    }

                    private static String siblingFile(String name) {
                        return siblingPath(name);
                    }

                    private static void loadFile(Properties p, String path) {
                        Path file = Path.of(path);
                        if (!Files.isRegularFile(file)) {
                            try (InputStream in = TestEnv.class.getClassLoader().getResourceAsStream(path)) {
                                if (in != null) {
                                    p.load(in);
                                }
                            } catch (Exception ignored) {
                                // optional file
                            }
                            return;
                        }
                        try (InputStream in = Files.newInputStream(file)) {
                            p.load(in);
                        } catch (Exception ignored) {
                            // optional file
                        }
                    }

                    public static String get(String key, String defaultValue) {
                        String envKey = key.toUpperCase(Locale.ROOT).replace('.', '_');
                        String fromEnv = System.getenv(envKey);
                        if (fromEnv != null && !fromEnv.isBlank()) {
                            return fromEnv.trim();
                        }
                        String fromProp = PROPS.getProperty(key);
                        if (fromProp != null && !fromProp.isBlank()) {
                            return fromProp.trim();
                        }
                        return defaultValue;
                    }

                    public static boolean getBoolean(String key, boolean defaultValue) {
                        String v = get(key, null);
                        if (v == null) {
                            return defaultValue;
                        }
                        return "true".equalsIgnoreCase(v) || "1".equals(v);
                    }

                    public static int getInt(String key, int defaultValue) {
                        String v = get(key, null);
                        if (v == null) {
                            return defaultValue;
                        }
                        try {
                            return Integer.parseInt(v.trim());
                        } catch (NumberFormatException e) {
                            return defaultValue;
                        }
                    }

                    public static String baseUrl() {
                        String env = System.getenv("API_BASE_URL");
                        if (env != null && !env.isBlank()) {
                            return env.trim();
                        }
                        return get("base.url", "%s");
                    }

                    public static String acceptLanguage() {
                        return get("accept.language", "en-US");
                    }

                    public static String departmentId() {
                        return get("test.department.id", "1");
                    }

                    public static String parentFolderId() {
                        return get("test.parent.folder.id", get("test.filter.parent.id", "1"));
                    }

                    public static String folderId() {
                        return get("test.folder.id", parentFolderId());
                    }

                    public static String pageNum() {
                        return String.valueOf(getInt("test.pagination.pageNum", 1));
                    }

                    public static String pageSize() {
                        return String.valueOf(getInt("test.pagination.pageSize", 10));
                    }

                    public static boolean tlsVerify() {
                        return getBoolean("tls.verify", true);
                    }

                    public static boolean bootstrapEnabled() {
                        return getBoolean("test.bootstrap.enabled", false);
                    }

                    public static boolean destructiveEnabled() {
                        return getBoolean("test.destructive.enabled", false);
                    }

                    public static boolean validateResponseSchema() {
                        return getBoolean("test.validateResponseSchema", false);
                    }
                }
                """.formatted(pkg, escapeJava(defaultBaseUrl));
    }

    private static String testAuthSource(String pkg, boolean egainAuth) {
        String egainCall = egainAuth
                ? """
                        String egain = EgainAuth.fetchBearerToken();
                        if (egain != null && !egain.isBlank()) {
                            return egain;
                        }
                        """
                : "";
        return """
                package %s;

                /**
                 * Resolves bearer token: env override, property file, optional eGain login.
                 */
                public final class TestAuth {

                    private TestAuth() {
                    }

                    public static String rawToken() {
                        String t = System.getenv("API_TOKEN");
                        if (t != null && !t.isBlank()) {
                            return t.trim();
                        }
                        t = System.getenv("API_BEARER_TOKEN");
                        if (t != null && !t.isBlank()) {
                            return t.trim();
                        }
                        t = System.getenv("INTEGRATION_TOKEN_CLIENT_APPLICATION");
                        if (t != null && !t.isBlank()) {
                            return t.trim();
                        }
                        t = TestEnv.get("auth.token", null);
                        if (t != null && !t.isBlank()) {
                            return t.trim();
                        }
                        %s
                        return "";
                    }

                    public static String bearerHeader() {
                        String t = rawToken();
                        return t.isEmpty() ? "" : "Bearer " + t;
                    }
                }
                """.formatted(pkg, egainCall);
    }

    private static String testHttpSource(String pkg) {
        return """
                package %s;

                import javax.net.ssl.SSLContext;
                import javax.net.ssl.TrustManager;
                import javax.net.ssl.X509TrustManager;
                import java.net.http.HttpClient;
                import java.security.cert.X509Certificate;
                import java.time.Duration;

                public final class TestHttp {

                    private TestHttp() {
                    }

                    public static HttpClient client() {
                        HttpClient.Builder builder = HttpClient.newBuilder()
                                .connectTimeout(Duration.ofSeconds(30));
                        if (!TestEnv.tlsVerify()) {
                            try {
                                TrustManager[] trustAll = new TrustManager[]{
                                        new X509TrustManager() {
                                            public void checkClientTrusted(X509Certificate[] c, String a) {}
                                            public void checkServerTrusted(X509Certificate[] c, String a) {}
                                            public X509Certificate[] getAcceptedIssuers() { return new X509Certificate[0]; }
                                        }
                                };
                                SSLContext ssl = SSLContext.getInstance("TLS");
                                ssl.init(null, trustAll, new java.security.SecureRandom());
                                builder.sslContext(ssl);
                            } catch (Exception e) {
                                throw new RuntimeException("Failed to configure TLS trust", e);
                            }
                        }
                        return builder.build();
                    }
                }
                """.formatted(pkg);
    }

    private static String testClientSource(String pkg) {
        return """
                package %s;

                import io.restassured.RestAssured;
                import io.restassured.specification.RequestSpecification;

                import static io.restassured.RestAssured.given;

                public final class TestClient {

                    private TestClient() {
                    }

                    public static void configureRestAssured() {
                        RestAssured.baseURI = TestEnv.baseUrl();
                        RestAssured.useRelaxedHTTPSValidation();
                    }

                    public static RequestSpecification givenAuth() {
                        RequestSpecification spec = given()
                                .header("Accept", "application/json")
                                .header("Accept-Language", TestEnv.acceptLanguage());
                        String token = TestAuth.rawToken();
                        if (token != null && !token.isEmpty()) {
                            spec = spec.header("Authorization", "Bearer " + token);
                        }
                        return spec;
                    }
                }
                """.formatted(pkg);
    }

    private static String testContextSource(String pkg) {
        return """
                package %s;

                import java.util.ArrayList;
                import java.util.Collections;
                import java.util.List;
                import java.util.concurrent.CopyOnWriteArrayList;

                /** Shared state for workflow and lifecycle tests. */
                public final class TestContext {

                    private static final CopyOnWriteArrayList<String> CREATED_IDS = new CopyOnWriteArrayList<>();
                    private static volatile String bootstrapParentFolderId;
                    private static volatile String bootstrapHierarchyRootId;

                    private TestContext() {
                    }

                    public static void trackCreatedId(String id) {
                        if (id != null && !id.isBlank()) {
                            CREATED_IDS.add(id);
                        }
                    }

                    public static List<String> createdIds() {
                        return Collections.unmodifiableList(new ArrayList<>(CREATED_IDS));
                    }

                    public static void clearCreatedIds() {
                        CREATED_IDS.clear();
                    }

                    public static String bootstrapParentFolderId() {
                        return bootstrapParentFolderId;
                    }

                    public static void setBootstrapParentFolderId(String id) {
                        bootstrapParentFolderId = id;
                    }

                    public static String bootstrapHierarchyRootId() {
                        return bootstrapHierarchyRootId;
                    }

                    public static void setBootstrapHierarchyRootId(String id) {
                        bootstrapHierarchyRootId = id;
                    }
                }
                """.formatted(pkg);
    }

    private static String egainAuthSource(String pkg) {
        return """
                package %s;

                import java.net.URI;
                import java.net.http.HttpClient;
                import java.net.http.HttpRequest;
                import java.net.http.HttpResponse;
                import java.time.Duration;

                /**
                 * eGain session login + JWT bearer exchange.
                 * Configure auth.login.url, auth.username, auth.password in test-env.properties.
                 */
                public final class EgainAuth {

                    private EgainAuth() {
                    }

                    public static String fetchBearerToken() {
                        String username = TestEnv.get("auth.username", null);
                        String password = TestEnv.get("auth.password", null);
                        if (username == null || password == null) {
                            return null;
                        }
                        try {
                            String loginUrl = TestEnv.get("auth.login.url",
                                    TestEnv.get("auth.oauth.tokenUrl", ""));
                            if (loginUrl == null || loginUrl.isBlank()) {
                                return null;
                            }
                            HttpClient client = TestHttp.client();
                            String sessionBody = "{\\"username\\":\\"" + escapeJson(username)
                                    + "\\",\\"password\\":\\"" + escapeJson(password) + "\\"}";
                            HttpRequest login = HttpRequest.newBuilder()
                                    .uri(URI.create(loginUrl))
                                    .timeout(Duration.ofSeconds(30))
                                    .header("Content-Type", "application/json")
                                    .header("Accept", "application/json")
                                    .POST(HttpRequest.BodyPublishers.ofString(sessionBody))
                                    .build();
                            HttpResponse<String> loginResp = client.send(login, HttpResponse.BodyHandlers.ofString());
                            if (loginResp.statusCode() >= 300) {
                                return null;
                            }
                            String sessionToken = extractJsonString(loginResp.body(), "sessionId");
                            if (sessionToken == null) {
                                sessionToken = extractJsonString(loginResp.body(), "access_token");
                            }
                            if (sessionToken == null) {
                                return null;
                            }
                            String exchangeUrl = TestEnv.get("auth.bearer.exchange.url", loginUrl + "/oauth2/token");
                            String exchangeBody = "{\\"grant_type\\":\\"client_credentials\\",\\"sessionId\\":\\""
                                    + escapeJson(sessionToken) + "\\"}";
                            HttpRequest exchange = HttpRequest.newBuilder()
                                    .uri(URI.create(exchangeUrl))
                                    .timeout(Duration.ofSeconds(30))
                                    .header("Content-Type", "application/json")
                                    .header("Accept", "application/json")
                                    .POST(HttpRequest.BodyPublishers.ofString(exchangeBody))
                                    .build();
                            HttpResponse<String> exchangeResp = client.send(exchange, HttpResponse.BodyHandlers.ofString());
                            if (exchangeResp.statusCode() >= 300) {
                                return sessionToken;
                            }
                            String bearer = extractJsonString(exchangeResp.body(), "access_token");
                            return bearer != null ? bearer : sessionToken;
                        } catch (Exception e) {
                            System.err.println("EgainAuth: " + e.getMessage());
                            return null;
                        }
                    }

                    private static String extractJsonString(String json, String field) {
                        if (json == null) {
                            return null;
                        }
                        String needle = "\\"" + field + "\\":\\"";
                        int i = json.indexOf(needle);
                        if (i < 0) {
                            return null;
                        }
                        int start = i + needle.length();
                        int end = json.indexOf('"', start);
                        return end > start ? json.substring(start, end) : null;
                    }

                    private static String escapeJson(String s) {
                        return s.replace("\\\\", "\\\\\\\\").replace("\\"", "\\\\\\"");
                    }
                }
                """.formatted(pkg);
    }

    private static String testEnvProperties(String defaultBaseUrl, boolean egainAuth) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated test environment — copy test-env.local.properties.example for secrets\n");
        sb.append("base.url=").append(defaultBaseUrl).append("\n");
        sb.append("accept.language=en-US\n");
        sb.append("tls.verify=false\n\n");
        sb.append("# Test data IDs (discover via GET /folders?departmentId=...)\n");
        sb.append("test.department.id=\n");
        sb.append("test.parent.folder.id=\n");
        sb.append("test.filter.parent.id=\n");
        sb.append("test.folder.id=\n");
        sb.append("test.prompt.id=\n\n");
        sb.append("test.pagination.pageNum=1\n");
        sb.append("test.pagination.pageSize=10\n\n");
        sb.append("test.bootstrap.enabled=false\n");
        sb.append("test.destructive.enabled=false\n");
        sb.append("test.validateResponseSchema=false\n\n");
        sb.append("# Auth — set API_TOKEN env or auth.token property\n");
        if (egainAuth) {
            sb.append("auth.provider=egain\n");
            sb.append("auth.login.url=\n");
            sb.append("auth.bearer.exchange.url=\n");
            sb.append("auth.username=\n");
            sb.append("auth.password=\n");
        }
        sb.append("auth.token=\n");
        return sb.toString();
    }

    private static String testEnvLocalExample(boolean egainAuth) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Local overrides — do not commit\n");
        sb.append("base.url=https://your-host.example/system/ws/knowledge/contentmgr/v4\n");
        if (egainAuth) {
            sb.append("auth.username=your-user\n");
            sb.append("auth.password=your-password\n");
            sb.append("auth.login.url=https://your-host.example/system/ws/v20/authentication/user/login\n");
        }
        sb.append("test.department.id=1001\n");
        sb.append("test.parent.folder.id=\n");
        sb.append("test.folder.id=\n");
        return sb.toString();
    }

    private static String runSmokeScript() {
        return """
                #!/usr/bin/env bash
                set -euo pipefail
                ROOT="$(cd "$(dirname "$0")" && pwd)"
                export TEST_ENV_FILE="${TEST_ENV_FILE:-$ROOT/test-env.properties}"
                cd "$ROOT/unit"
                mvn -q test -Dtest='FoldersApiTest#testGetSubFolders_ValidRequest' || true
                cd "$ROOT/integration"
                mvn -q test -Dtest='FoldersIntegrationTest#testGetSubFolders_Success_ClientApplication' || true
                echo "Smoke tests finished (see output above)."
                """;
    }

    private static String runSmokeBat() {
        return """
                @echo off
                set ROOT=%~dp0
                if not defined TEST_ENV_FILE set TEST_ENV_FILE=%ROOT%test-env.properties
                cd /d %ROOT%unit
                call mvn -q test -Dtest=FoldersApiTest#testGetSubFolders_ValidRequest
                cd /d %ROOT%integration
                call mvn -q test -Dtest=FoldersIntegrationTest#testGetSubFolders_Success_ClientApplication
                echo Smoke tests finished.
                """;
    }

    private static String aggregatorPom() {
        return """
                <?xml version="1.0" encoding="UTF-8"?>
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example.api</groupId>
                    <artifactId>generated-api-tests</artifactId>
                    <version>1.0.0</version>
                    <packaging>pom</packaging>
                    <modules>
                        <module>unit</module>
                        <module>integration</module>
                        <module>nfr</module>
                        <module>performance</module>
                        <module>security</module>
                        <module>sequence-java</module>
                    </modules>
                </project>
                """;
    }

    private static String readmeTests(boolean egainAuth) {
        return """
                # Generated API Tests

                ## Quick start

                1. Copy `test-env.local.properties.example` to `test-env.local.properties` and fill in values.
                2. Set `TEST_ENV_FILE` to the absolute path of your properties file (optional if running from this directory).
                3. Run smoke: `./run-smoke.sh` (or `run-smoke.bat` on Windows).
                4. Run all Java modules: `mvn test` from this directory.

                ## Configuration

                All Java test modules load `test-env.properties` via `TestEnv`. Environment variables override properties.

                Key properties: `base.url`, `test.department.id`, `test.parent.folder.id`, `test.folder.id`, `accept.language`.
                """
                + (egainAuth ? "\n\neGain auth: set `auth.username`, `auth.password`, `auth.login.url` or export `API_TOKEN`.\n" : "");
    }

    private static String escapeJava(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
